"""
Playwright tests — generated by Agentic SDLC pipeline. Do not edit manually.
"""
import pytest

@pytest.mark.scenario("SC-008")
@pytest.mark.requirement("AC-008")
def test_sc_008_success_message_appears_on_cart_add(page):
    """SC-008: Success message appears on cart add."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("load", timeout=30000)
    page.locator(".product-thumb").first.hover()
    page.wait_for_timeout(500)
    page.locator("button.btn-cart:visible").first.click(force=True)
    page.wait_for_timeout(2000)
    success = page.locator(".toast-body, .alert-success, .toast")
    assert success.count() > 0, "No success notification after adding to cart"
